"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

const money = new Intl.NumberFormat("en-LK", { style: "currency", currency: "LKR", minimumFractionDigits: 2 });
const methods = ["Company Bank", "Cash", "Credit Card", "Debit Card", "Bank Transfer", "Payment Gateway", "Founder Account"];
const entryTypes = {
  "Operating Expense": { kind:"Expense", accounts:["Expense"] },
  "Operating Income": { kind:"Income", accounts:["Income"] },
  "Company Registration Expense": { kind:"Expense", accounts:["Expense"], defaultAccount:"5095" },
  "Founder-Funded Expense": { kind:"Expense", accounts:["Expense","Asset"] },
  "Founder Capital Contribution": { kind:"Income", accounts:["Equity"] },
  "Founder Reimbursement": { kind:"Expense", accounts:["Liability"] },
  "Director Drawing / Distribution": { kind:"Expense", accounts:["Equity"] },
  "Refund / Chargeback": { kind:"Expense", accounts:["Expense","Liability"] },
  "Organizer Payable": { kind:"Income", accounts:["Liability"] },
  "Cash / Bank Transfer": { kind:"Expense", accounts:["Asset"] },
  "Accounting Adjustment": { kind:"Expense", accounts:["Asset","Liability","Equity","Income","Expense"] }
};
const paidByOptions = ["Pasindu", "Wicky", "Company"];
const empty = { id:"", entryType:"Operating Expense", kind:"Expense", date:new Date().toISOString().slice(0,10), accountCode:"", cashAccountId:"", counterpartyId:"", paymentMethod:"", paidBy:"Company", amount:"", taxAmount:"0", description:"", referenceNo:"", proofUrl:"", notes:"", status:"Posted" };
const blankFilters = { q:"", kind:"", status:"", account:"", from:"", to:"" };
const allowedStaff = ["bgpsandaruwan@gmail.com", "wickycinema@gmail.com"];
const rowToForm = r => ({ id:r.id, entryType:r.entry_type||(r.kind==="Income"?"Operating Income":"Operating Expense"), kind:r.kind, date:r.transaction_date, accountCode:r.account_code||"", cashAccountId:r.cash_account_id||"", counterpartyId:r.counterparty_id||"", paymentMethod:r.payment_method, paidBy:r.paid_by, amount:String(r.amount), taxAmount:String(r.tax_amount||0), description:r.description, referenceNo:r.reference_no||"", proofUrl:r.proof_url||"", notes:r.notes||"", status:r.status||"Posted" });

export default function Home() {
  const [session,setSession]=useState(null), [authReady,setAuthReady]=useState(false), [authError,setAuthError]=useState("");
  const [tab,setTab]=useState("dashboard"), [rows,setRows]=useState([]), [accounts,setAccounts]=useState([]), [cashAccounts,setCashAccounts]=useState([]), [parties,setParties]=useState([]), [audits,setAudits]=useState([]), [founders,setFounders]=useState([]), [founderActivity,setFounderActivity]=useState([]), [companyPerformance,setCompanyPerformance]=useState(null), [trialBalance,setTrialBalance]=useState([]);
  const [form,setForm]=useState(empty), [filters,setFilters]=useState(blankFilters), [month,setMonth]=useState(new Date().toISOString().slice(0,7)), [status,setStatus]=useState(""), [busy,setBusy]=useState(false);
  const [fiscalPeriods,setFiscalPeriods]=useState([]), [allocations,setAllocations]=useState([]), [allocationForm,setAllocationForm]=useState({periodId:"",profitAfterTax:"",reinvestment:"0",reference:"",notes:"",status:"Draft"});
  const [auditFilters,setAuditFilters]=useState({q:"",action:"",table:""});
  const [reportConfig,setReportConfig]=useState({type:"Monthly",date:new Date().toISOString().slice(0,10),periodId:"",director:"Pasindu",from:"",to:""});

  useEffect(()=>{
    let active=true;
    if(!supabase){setAuthError("Supabase environment variables are missing.");setAuthReady(true);return;}
    const timeout=setTimeout(()=>{if(active){setAuthError("Authentication took too long. Check the Supabase connection and refresh.");setAuthReady(true)}},5000);
    supabase.auth.getSession().then(({data,error})=>{if(!active)return;clearTimeout(timeout);if(error)setAuthError(error.message);const current=data?.session||null;if(current&&!allowedStaff.includes(current.user.email?.toLowerCase())){setAuthError("This account is not authorized for nZO company books.");supabase.auth.signOut();setSession(null)}else setSession(current);setAuthReady(true)}).catch(error=>{if(active){clearTimeout(timeout);setAuthError(error.message);setAuthReady(true)}});
    const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{if(active){if(s&&!allowedStaff.includes(s.user.email?.toLowerCase())){setAuthError("This account is not authorized for nZO company books.");supabase.auth.signOut();setSession(null)}else setSession(s);setAuthReady(true)}});
    return()=>{active=false;clearTimeout(timeout);subscription.unsubscribe()};
  },[]);
  useEffect(()=>{ if(session) loadAll(); },[session]);

  async function loadAll(){
    setBusy(true); setStatus("Loading company books…");
    const [tx,coa,cash,cp,audit,founderData,founderTrace,performance,tb,periods,allocationData]=await Promise.all([
      supabase.from("transactions").select("*, chart_of_accounts(name,account_type), cash_accounts(name), counterparties(name)").order("transaction_date",{ascending:false}),
      supabase.from("chart_of_accounts").select("*").eq("is_active",true).order("code"),
      supabase.from("cash_accounts").select("*").eq("is_active",true).order("name"),
      supabase.from("counterparties").select("*").eq("is_active",true).order("name"),
      supabase.from("audit_logs").select("*").order("changed_at",{ascending:false}).limit(100),
      supabase.from("founder_financial_summary").select("*").order("code"),
      supabase.from("founder_activity").select("*").order("journal_date",{ascending:false}),
      supabase.from("company_performance_summary").select("*").maybeSingle(),
      supabase.from("trial_balance").select("*").order("code"),
      supabase.from("fiscal_periods").select("*").order("starts_on",{ascending:false}),
      supabase.from("profit_allocations").select("*, fiscal_periods(name)").order("created_at",{ascending:false})
    ]);
    const error=tx.error||coa.error||cash.error||cp.error;
    if(error) setStatus(`Setup required: ${error.message}`); else {setRows(tx.data);setAccounts(coa.data);setCashAccounts(cash.data);setParties(cp.data);setAudits(audit.data||[]);setFounders(founderData.data||[]);setFounderActivity(founderTrace.data||[]);setCompanyPerformance(performance.data||null);setTrialBalance(tb.data||[]);setFiscalPeriods(periods.data||[]);setAllocations(allocationData.data||[]);setStatus(`${tx.data.length} ledger entries loaded`)}
    setBusy(false);
  }

  const filtered=useMemo(()=>rows.filter(r=>(!filters.q||JSON.stringify(r).toLowerCase().includes(filters.q.toLowerCase()))&&(!filters.kind||r.kind===filters.kind)&&(!filters.status||r.status===filters.status)&&(!filters.account||r.account_code===filters.account)&&(!filters.from||r.transaction_date>=filters.from)&&(!filters.to||r.transaction_date<=filters.to)),[rows,filters]);
  const posted=useMemo(()=>rows.filter(r=>r.status==="Posted"),[rows]);
  const monthly=useMemo(()=>posted.filter(r=>r.transaction_date.startsWith(month)),[posted,month]);
  const stats=calc(posted), monthlyStats=calc(monthly), split=splitStats(posted), monthlySplit=splitStats(monthly);
  const byAccount=useMemo(()=>monthly.reduce((a,r)=>{const key=`${r.account_code} · ${r.chart_of_accounts?.name||r.category}`;a[key]=(a[key]||0)+(r.kind==="Income"?Number(r.amount):-Number(r.amount));return a},{}),[monthly]);

  const filteredAudits=useMemo(()=>audits.filter(a=>(!auditFilters.q||JSON.stringify(a).toLowerCase().includes(auditFilters.q.toLowerCase()))&&(!auditFilters.action||a.action===auditFilters.action)&&(!auditFilters.table||a.table_name===auditFilters.table)),[audits,auditFilters]);
  const reportRows=useMemo(()=>posted.filter(r=>{if(reportConfig.type==="Monthly")return r.transaction_date.startsWith(month);if(reportConfig.type==="Daily")return r.transaction_date===reportConfig.date;if(reportConfig.type==="Financial Year"){const p=fiscalPeriods.find(x=>x.id===(reportConfig.periodId||fiscalPeriods[0]?.id));return p&&r.transaction_date>=p.starts_on&&r.transaction_date<=p.ends_on}if(reportConfig.type==="Director-wise"){const person=r.paid_by==="Pradeep"?"Wicky":r.paid_by;return person===reportConfig.director&&(!reportConfig.from||r.transaction_date>=reportConfig.from)&&(!reportConfig.to||r.transaction_date<=reportConfig.to)}return true}),[posted,reportConfig,month,fiscalPeriods]);
  const viewedReportStats=calc(reportRows), viewedReportSplit=splitStats(reportRows);

  async function signIn(e){e.preventDefault();setAuthError("");const fd=new FormData(e.currentTarget),email=String(fd.get("email")).trim().toLowerCase();if(!allowedStaff.includes(email)){setAuthError("This email is not authorized for nZO company books.");return}const {error}=await supabase.auth.signInWithPassword({email,password:fd.get("password")});if(error)setAuthError(error.message)}
  async function save(e){e.preventDefault();setBusy(true);const kind=entryTypes[form.entryType]?.kind||form.kind;const payload={...(form.id&&{id:form.id}),entry_type:form.entryType,kind,transaction_date:form.date,category:accounts.find(a=>a.code===form.accountCode)?.name||"Other",account_code:form.accountCode,cash_account_id:form.cashAccountId||null,counterparty_id:form.counterpartyId||null,payment_method:form.paymentMethod,paid_by:form.paidBy,amount:Number(form.amount),tax_amount:Number(form.taxAmount||0),description:form.description,reference_no:form.referenceNo,proof_url:form.proofUrl,notes:form.notes,status:form.status,updated_by:session.user.id,...(!form.id&&{created_by:session.user.id})};const {error}=form.id?await supabase.from("transactions").update(payload).eq("id",form.id):await supabase.from("transactions").insert(payload);if(error)setStatus(`Save failed: ${error.message}`);else{setForm(empty);setTab("ledger");await loadAll()}setBusy(false)}
  async function voidEntry(r){const confirmed=confirm(`Are you sure you want to delete ${r.id}?\n\n${r.description}\n${money.format(r.amount)}\n\nThe accounting journal will be reversed and the audit history will be retained.`);if(!confirmed)return;setBusy(true);const {data,error}=await supabase.from("transactions").delete().eq("id",r.id).select("id");if(error)setStatus(`Delete failed: ${error.message}`);else if(!data?.length)setStatus(`Delete failed: ${r.id} was not removed. Please refresh and try again.`);else{setStatus(`${r.id} deleted. Journal reversed and audit retained.`);await loadAll()}setBusy(false)}
  function exportCsv(){const head=["ID","Date","Status","Kind","Account","Description","Reference","Amount","Tax","Payment Method"];const body=filtered.map(r=>[r.id,r.transaction_date,r.status,r.kind,r.account_code,r.description,r.reference_no,r.amount,r.tax_amount,r.payment_method]);const csv=[head,...body].map(x=>x.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`nzo-ledger-${new Date().toISOString().slice(0,10)}.csv`;a.click()}
  function download(name,head,body){const csv=[head,...body].map(x=>x.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=name;a.click()}
  function exportViewedReport(){const label=reportConfig.type.toLowerCase().replaceAll(" ","-");download(`nzo-${label}-report-${new Date().toISOString().slice(0,10)}.csv`,["Date","ID","Entry Type","Account","Category","Description","Paid/Received By","Payment Method","Status","Amount LKR"],reportRows.map(r=>[r.transaction_date,r.id,r.entry_type||r.kind,r.account_code,r.chart_of_accounts?.name||r.category,r.description,r.paid_by,r.payment_method,r.status,r.amount]))}
  function exportAudit(){download(`nzo-audit-${new Date().toISOString().slice(0,10)}.csv`,["When","Table","Action","Record","Changed By","Old Data","New Data"],filteredAudits.map(a=>[a.changed_at,a.table_name,a.action,a.record_id,a.changed_by,JSON.stringify(a.old_data),JSON.stringify(a.new_data)]))}
  async function saveAllocation(e){e.preventDefault();setBusy(true);const payload={fiscal_period_id:allocationForm.periodId,profit_after_tax:Number(allocationForm.profitAfterTax),reinvestment_amount:Number(allocationForm.reinvestment),resolution_reference:allocationForm.reference,notes:allocationForm.notes,status:allocationForm.status,created_by:session.user.id,...(allocationForm.status!=="Draft"&&{approved_by:session.user.id,approved_at:new Date().toISOString()})};const {error}=await supabase.from("profit_allocations").upsert(payload,{onConflict:"fiscal_period_id"});if(error)setStatus(`Allocation failed: ${error.message}`);else{setAllocationForm({periodId:"",profitAfterTax:"",reinvestment:"0",reference:"",notes:"",status:"Draft"});await loadAll()}setBusy(false)}

  if(!authReady)return <div className="splash">Opening secure company books…</div>;
  if(!session)return <Auth signIn={signIn} error={authError}/>;
  const nav=[["dashboard","Overview"],["new","New entry"],["ledger","General ledger"],["reports","Reports"],["founders","Founders"],["accounts","Chart of accounts"],["audit","Audit trail"]];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="ep-mark">EP</span><strong>Business Administration</strong><small>nZO Innovations · Internal</small></div><nav>{nav.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="user"><small>Signed in</small><span>{session.user.email}</span><button onClick={()=>supabase.auth.signOut()}>Sign out</button></div></aside><main className="workspace"><header><div><p className="eyebrow">Entertain Passport · Company books</p><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1></div><div className="sync"><i className={busy?"busy":""}/>{status}</div></header>
    {tab==="dashboard"&&<><section className="metric-grid"><Metric label="Revenue" value={money.format(stats.income)} tone="green"/><Metric label="Operating expenses" value={money.format(stats.expense)} tone="red"/><Metric label="Net cash result" value={money.format(stats.net)} tone={stats.net>=0?"green":"red"}/><Metric label="Posted entries" value={stats.count}/></section><SplitPanel data={split} title="50/50 founder allocation · All time"/><section className="two-col"><Panel title="This month" action={<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/>}><div className="mini-stats"><span>Income <b>{money.format(monthlyStats.income)}</b></span><span>Expense <b>{money.format(monthlyStats.expense)}</b></span><span>Net <b>{money.format(monthlyStats.net)}</b></span></div></Panel><Panel title="Financial controls"><ul className="control-list"><li><b>Supabase Auth</b><span>Active staff access</span></li><li><b>Row Level Security</b><span>Authenticated policies</span></li><li><b>Audit trail</b><span>Insert, edit and void history</span></li><li><b>Currency</b><span>LKR · 2 decimal places</span></li></ul></Panel></section><Panel title="Recent activity"><LedgerTable rows={posted.slice(0,6)} accounts={accounts} edit={r=>{setForm(rowToForm(r));setTab("new")}} voidEntry={voidEntry}/></Panel></>}
    {tab==="new"&&<Panel title={form.id?`Edit ${form.id}`:"Record company transaction"}><form className="entry-form" onSubmit={save}><Field label="Entry type"><Select value={form.entryType} set={v=>setForm({...form,entryType:v,kind:entryTypes[v].kind,accountCode:entryTypes[v].defaultAccount||""})} items={Object.keys(entryTypes)}/></Field><Field label="Date"><input required type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="Status"><Select value={form.status} set={v=>setForm({...form,status:v})} items={["Draft","Posted"]}/></Field><Field label="Category / ledger account"><Select required value={form.accountCode} set={v=>setForm({...form,accountCode:v})} items={accounts.filter(a=>entryTypes[form.entryType].accounts.includes(a.account_type)).map(a=>[a.code,`${a.code} · ${a.name}`])} placeholder="Choose category"/></Field><Field label="Cash / bank account"><Select value={form.cashAccountId} set={v=>setForm({...form,cashAccountId:v})} items={cashAccounts.map(a=>[a.id,a.name])} placeholder="Choose account"/></Field><Field label="Counterparty"><Select value={form.counterpartyId} set={v=>setForm({...form,counterpartyId:v})} items={parties.map(p=>[p.id,p.name])} placeholder="Optional"/></Field><Field label="Payment method"><Select required value={form.paymentMethod} set={v=>setForm({...form,paymentMethod:v})} items={methods} placeholder="Choose method"/></Field><Field label="Paid / received by"><Select value={form.paidBy} set={v=>setForm({...form,paidBy:v})} items={paidByOptions}/></Field><Field label="Amount (LKR)"><input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="Tax / WHT (LKR)"><input type="number" min="0" step="0.01" value={form.taxAmount} onChange={e=>setForm({...form,taxAmount:e.target.value})}/></Field><Field label="Reference"><input value={form.referenceNo} onChange={e=>setForm({...form,referenceNo:e.target.value})} placeholder="Invoice / campaign / order ID"/></Field><Field label="Proof URL"><input type="url" value={form.proofUrl} onChange={e=>setForm({...form,proofUrl:e.target.value})} placeholder="Receipt or invoice link"/></Field><Field label="Description" wide><input required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="Internal notes" wide><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="form-actions"><button disabled={busy}>{form.id?"Save changes":"Post entry"}</button><button type="button" className="ghost" onClick={()=>setForm(empty)}>Clear</button></div></form></Panel>}
    {tab==="ledger"&&<><Panel title="Filters" action={<button className="ghost compact" onClick={exportCsv}>Export CSV</button>}><div className="filter-grid"><input placeholder="Search ledger…" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><Select value={filters.kind} set={v=>setFilters({...filters,kind:v})} items={["Income","Expense"]} placeholder="All types"/><Select value={filters.status} set={v=>setFilters({...filters,status:v})} items={["Draft","Posted","Void"]} placeholder="All statuses"/><Select value={filters.account} set={v=>setFilters({...filters,account:v})} items={accounts.map(a=>[a.code,`${a.code} · ${a.name}`])} placeholder="All accounts"/><input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></div></Panel><Panel title={`${filtered.length} ledger entries`}><LedgerTable rows={filtered} accounts={accounts} edit={r=>{setForm(rowToForm(r));setTab("new")}} voidEntry={voidEntry}/></Panel></>}
    {tab==="reports"&&<><Panel title="Generate report" action={<button className="compact" disabled={!reportRows.length} onClick={exportViewedReport}>Download viewed report</button>}><div className="report-builder"><Field label="Report type"><Select value={reportConfig.type} set={v=>setReportConfig({...reportConfig,type:v})} items={["Financial Year","Monthly","Daily","Director-wise"]}/></Field>{reportConfig.type==="Financial Year"&&<Field label="Financial year (April–March)"><Select value={reportConfig.periodId||fiscalPeriods[0]?.id||""} set={v=>setReportConfig({...reportConfig,periodId:v})} items={fiscalPeriods.map(p=>[p.id,`${p.name} · ${p.starts_on} to ${p.ends_on}`])}/></Field>}{reportConfig.type==="Monthly"&&<Field label="Month"><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></Field>}{reportConfig.type==="Daily"&&<Field label="Date"><input type="date" value={reportConfig.date} onChange={e=>setReportConfig({...reportConfig,date:e.target.value})}/></Field>}{reportConfig.type==="Director-wise"&&<><Field label="Director"><Select value={reportConfig.director} set={v=>setReportConfig({...reportConfig,director:v})} items={["Pasindu","Wicky"]}/></Field><Field label="From"><input type="date" value={reportConfig.from} onChange={e=>setReportConfig({...reportConfig,from:e.target.value})}/></Field><Field label="To"><input type="date" value={reportConfig.to} onChange={e=>setReportConfig({...reportConfig,to:e.target.value})}/></Field></>}</div></Panel><Panel title={`${reportConfig.type} report`} action={<span className="badge-count">{reportRows.length} records</span>}><ReportSummary stats={viewedReportStats} split={viewedReportSplit} director={reportConfig.type==="Director-wise"?reportConfig.director:""}/></Panel><section className="two-col"><Panel title="Income by account"><ReportBreakdown rows={reportRows.filter(r=>r.kind==="Income")}/></Panel><Panel title="Expenses by account"><ReportBreakdown rows={reportRows.filter(r=>r.kind==="Expense")}/></Panel></section><Panel title="Report details"><ReportRecords rows={reportRows}/></Panel></>}
    {tab==="founders"&&<><section className="metric-grid report"><Metric label="Company revenue" value={money.format(companyPerformance?.total_income||0)} tone="green"/><Metric label="Company expenses" value={money.format(companyPerformance?.total_expenses||0)} tone="red"/><Metric label="Net company profit" value={money.format(companyPerformance?.net_profit||0)}/></section><section className="founder-grid">{founders.map(f=><article className="founder-card" key={f.id}><p className="eyebrow">Co-Founder · {f.position}</p><h2>{f.full_name}</h2><strong>{Number(f.ownership_percent).toFixed(2)}%</strong><dl><div><dt>Capital introduced</dt><dd>{money.format(f.capital_introduced)}</dd></div><div><dt>Personally funded</dt><dd>{money.format(f.personally_funded)}</dd></div><div><dt>Reimbursed</dt><dd>{money.format(f.reimbursed)}</dd></div><div><dt>Company currently owes</dt><dd>{money.format(f.current_account_due)}</dd></div><div><dt>Allocated profit share</dt><dd>{money.format(f.allocated_profit)}</dd></div><div><dt>Reinvested share</dt><dd>{money.format(f.reinvested_profit)}</dd></div><div><dt>Drawings / distributions</dt><dd>{money.format(f.drawings)}</dd></div><div><dt>Remaining distributable</dt><dd>{money.format(f.remaining_distribution)}</dd></div></dl></article>)}{!founders.length&&<Panel title="Founder analytics setup required"><p>Run migrations 004 and 006 to activate the 50/50 founder register and detailed allocation reporting.</p></Panel>}</section><Panel title="Founder transaction trace"><div className="table-wrap"><table><thead><tr><th>Date / Journal</th><th>Founder</th><th>Activity</th><th>Account</th><th className="right">Debit</th><th className="right">Credit</th></tr></thead><tbody>{founderActivity.map(a=><tr key={`${a.journal_id}-${a.account_code}`}><td>{a.journal_date}<small>{a.journal_no}</small></td><td>{a.full_name}</td><td>{a.activity_type}<small>{a.memo}</small></td><td><code>{a.account_code}</code><small>{a.account_name}</small></td><td className="right">{money.format(a.debit)}</td><td className="right">{money.format(a.credit)}</td></tr>)}{!founderActivity.length&&<tr><td colSpan="6">No founder-related journals recorded yet.</td></tr>}</tbody></table></div></Panel><Panel title="Accounting treatment"><div className="accounting-note"><p><b>Company performance is not split transaction by transaction.</b> nZO recognizes all company revenue and expenses. The 50/50 agreement is represented in ordinary share capital and approved distributable equity.</p><p>Profit allocation is calculated only after tax provisions and a documented reinvestment decision. Personally funded company costs, reimbursements, drawings, and remaining distributions are traced separately for each Director.</p></div></Panel></>}
    {tab==="accounts"&&<><Panel title="nZO Chart of Accounts"><table><thead><tr><th>Code</th><th>Account</th><th>Type</th><th>Purpose</th></tr></thead><tbody>{accounts.map(a=><tr key={a.code}><td><code>{a.code}</code></td><td><b>{a.name}</b></td><td><span className={`pill ${a.account_type.toLowerCase()}`}>{a.account_type}</span></td><td>{a.description}</td></tr>)}</tbody></table></Panel><Panel title="Trial balance"><div className="table-wrap"><table><thead><tr><th>Code</th><th>Account</th><th>Type</th><th className="right">Balance</th></tr></thead><tbody>{trialBalance.filter(a=>Number(a.balance)!==0).map(a=><tr key={a.code}><td><code>{a.code}</code></td><td>{a.name}</td><td>{a.account_type}</td><td className="right">{money.format(Math.abs(Number(a.balance)))}</td></tr>)}</tbody></table></div></Panel></>}
    {tab==="audit"&&<><Panel title="Audit filters" action={<button className="ghost compact" onClick={exportAudit}>Export audit</button>}><div className="audit-filters"><input placeholder="Search record, user or change…" value={auditFilters.q} onChange={e=>setAuditFilters({...auditFilters,q:e.target.value})}/><Select value={auditFilters.action} set={v=>setAuditFilters({...auditFilters,action:v})} items={["INSERT","UPDATE","DELETE"]} placeholder="All actions"/><Select value={auditFilters.table} set={v=>setAuditFilters({...auditFilters,table:v})} items={[...new Set(audits.map(a=>a.table_name))]} placeholder="All modules"/></div></Panel><Panel title={`${filteredAudits.length} audited changes`}><div className="table-wrap"><table><thead><tr><th>When</th><th>Module / Record</th><th>Action</th><th>Changed by</th><th>Change detail</th></tr></thead><tbody>{filteredAudits.map(a=><tr key={a.id}><td>{new Date(a.changed_at).toLocaleString("en-LK")}<small>{new Date(a.changed_at).toISOString()}</small></td><td><b>{a.table_name}</b><small>{a.record_id}</small></td><td><span className={`pill ${a.action.toLowerCase()}`}>{a.action}</span></td><td>{a.changed_by||"System / migration"}</td><td><details><summary>View before / after</summary><div className="audit-detail"><div><b>Before</b><pre>{JSON.stringify(a.old_data,null,2)||"—"}</pre></div><div><b>After</b><pre>{JSON.stringify(a.new_data,null,2)||"—"}</pre></div></div></details></td></tr>)}{!filteredAudits.length&&<tr><td colSpan="5">No audit changes match these filters.</td></tr>}</tbody></table></div></Panel></>}
    {tab==="founders"&&<ProfitAllocation form={allocationForm} setForm={setAllocationForm} periods={fiscalPeriods} allocations={allocations} save={saveAllocation} busy={busy}/>}
  </main></div>;
}

function Auth({signIn,error}){return <div className="auth-page"><section className="auth-story"><div className="hero-mark">EP</div><p className="eyebrow">nZO Innovations</p><h1>Company books,<br/>under control.</h1><p>Internal administration and accounting for the company operating Entertain Passport.</p><div className="auth-points"><span>General ledger</span><span>Cash oversight</span><span>Audit-ready</span></div></section><form className="auth-card" onSubmit={signIn}><div className="logo ep-mark">EP</div><h2>Staff sign in</h2><p>Entertain Passport internal administration</p><Field label="Email"><input required type="email" name="email" autoComplete="email"/></Field><Field label="Password"><input required type="password" name="password" autoComplete="current-password"/></Field><button>Sign in securely</button>{error&&<p className="error">{error}</p>}</form></div>}
function calc(rows){return rows.reduce((a,r)=>{const n=Number(r.amount),type=r.chart_of_accounts?.account_type;if(type==="Income"||(!type&&r.kind==="Income"))a.income+=n;if(type==="Expense"||(!type&&r.kind==="Expense"))a.expense+=n;a.count++;a.net=a.income-a.expense;return a},{income:0,expense:0,net:0,count:0})}
function splitStats(rows){const s=rows.reduce((a,r)=>{const n=Number(r.amount||0),person=r.paid_by==="Pradeep"?"Wicky":r.paid_by;if(r.kind==="Expense"){a.expense+=n;if(person==="Pasindu")a.pasinduPaid+=n;if(person==="Wicky")a.wickyPaid+=n}else if(r.kind==="Income"){a.income+=n;if(person==="Pasindu")a.pasinduReceived+=n;if(person==="Wicky")a.wickyReceived+=n}return a},{expense:0,income:0,pasinduPaid:0,wickyPaid:0,pasinduReceived:0,wickyReceived:0});s.expenseShare=s.expense/2;s.incomeShare=s.income/2;s.pasinduExpensePosition=s.pasinduPaid-s.expenseShare;s.wickyExpensePosition=s.wickyPaid-s.expenseShare;s.pasinduIncomePosition=s.incomeShare-s.pasinduReceived;s.wickyIncomePosition=s.incomeShare-s.wickyReceived;const personalIncome=s.pasinduReceived+s.wickyReceived;s.pasinduSettlement=s.pasinduPaid-s.expenseShare-s.pasinduReceived+personalIncome/2;s.wickySettlement=-s.pasinduSettlement;return s}
function SplitPanel({data,title}){const creditor=data.pasinduSettlement>0?"Pasindu":data.pasinduSettlement<0?"Wicky":"",debtor=creditor==="Pasindu"?"Wicky":creditor==="Wicky"?"Pasindu":"",due=Math.abs(data.pasinduSettlement);return <Panel title={title} action={<span className="share-badge">50% : 50%</span>}><div className="split-grid"><div><span>Total expenses</span><b>{money.format(data.expense)}</b></div><div><span>Each founder expense share</span><b>{money.format(data.expenseShare)}</b></div><div><span>Pasindu actually paid</span><b>{money.format(data.pasinduPaid)}</b></div><div><span>Wicky actually paid</span><b>{money.format(data.wickyPaid)}</b></div><div><span>Each founder income allocation</span><b>{money.format(data.incomeShare)}</b></div><div className="settlement"><span>Balancing position</span><b>{creditor?`${debtor} owes ${creditor} ${money.format(due)}`:"Balanced"}</b></div></div><p className="allocation-note">This is the founders’ internal 50/50 management allocation. Company statutory revenue and expenses remain recorded at 100% in nZO’s books.</p></Panel>}
function ReportSummary({stats,split,director}){const directorPaid=director==="Pasindu"?split.pasinduPaid:split.wickyPaid;return <table className="statement-table"><tbody><tr><th>Total income</th><td className="right positive">{money.format(stats.income)}</td></tr><tr><th>Total expenses</th><td className="right negative">{money.format(stats.expense)}</td></tr><tr className="statement-total"><th>Net result</th><td className="right">{money.format(stats.net)}</td></tr>{director&&<><tr><th>{director} actually paid</th><td className="right">{money.format(directorPaid)}</td></tr><tr><th>{director} 50% expense responsibility</th><td className="right">{money.format(split.expenseShare)}</td></tr><tr><th>{director} 50% income allocation</th><td className="right">{money.format(split.incomeShare)}</td></tr></>}</tbody></table>}
function ReportBreakdown({rows}){const grouped=rows.reduce((a,r)=>{const k=`${r.account_code||"—"} · ${r.chart_of_accounts?.name||r.category}`;a[k]=(a[k]||0)+Number(r.amount);return a},{});return <table><thead><tr><th>Account</th><th className="right">Amount</th></tr></thead><tbody>{Object.entries(grouped).sort((a,b)=>b[1]-a[1]).map(([k,v])=><tr key={k}><td>{k}</td><td className="right">{money.format(v)}</td></tr>)}{!rows.length&&<tr><td colSpan="2">No records.</td></tr>}</tbody></table>}
function ReportRecords({rows}){return <div className="table-wrap"><table><thead><tr><th>Date</th><th>Type / Account</th><th>Description</th><th>Paid / Received By</th><th className="right">Amount</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.transaction_date}</td><td>{r.entry_type||r.kind}<small>{r.account_code} · {r.chart_of_accounts?.name||r.category}</small></td><td>{r.description}<small>{r.reference_no}</small></td><td>{r.paid_by}<small>{r.payment_method}</small></td><td className={`right amount ${r.kind.toLowerCase()}`}>{money.format(r.amount)}</td></tr>)}{!rows.length&&<tr><td colSpan="5">No posted records for this period.</td></tr>}</tbody></table></div>}
function ProfitAllocation({form,setForm,periods,allocations,save,busy}){const distributable=Math.max(0,Number(form.profitAfterTax||0)-Number(form.reinvestment||0));return <><Panel title="Profit and reinvestment resolution"><form className="allocation-form" onSubmit={save}><Field label="Fiscal period"><Select value={form.periodId} set={v=>setForm({...form,periodId:v})} items={periods.map(p=>[p.id,p.name])} placeholder="Choose fiscal period"/></Field><Field label="Profit after tax (LKR)"><input required min="0" step="0.01" type="number" value={form.profitAfterTax} onChange={e=>setForm({...form,profitAfterTax:e.target.value})}/></Field><Field label="Reinvest in company (LKR)"><input required min="0" max={form.profitAfterTax||undefined} step="0.01" type="number" value={form.reinvestment} onChange={e=>setForm({...form,reinvestment:e.target.value})}/></Field><Field label="Resolution reference"><input required value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})} placeholder="Board minute / resolution"/></Field><Field label="Status"><Select value={form.status} set={v=>setForm({...form,status:v})} items={["Draft","Approved"]}/></Field><div className="allocation-preview"><span>Distributable</span><b>{money.format(distributable)}</b><small>{money.format(distributable/2)} per founder</small></div><Field label="Notes" wide><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><button disabled={busy}>Save allocation</button></form></Panel><Panel title="Allocation history"><table><thead><tr><th>Period</th><th>Status</th><th className="right">After-tax profit</th><th className="right">Reinvested</th><th className="right">Distributable</th><th>Resolution</th></tr></thead><tbody>{allocations.map(a=><tr key={a.id}><td>{a.fiscal_periods?.name}</td><td><span className={`pill ${a.status.toLowerCase()}`}>{a.status}</span></td><td className="right">{money.format(a.profit_after_tax)}</td><td className="right">{money.format(a.reinvestment_amount)}</td><td className="right">{money.format(a.distributable_amount)}</td><td>{a.resolution_reference}</td></tr>)}{!allocations.length&&<tr><td colSpan="6">No profit allocation resolutions recorded.</td></tr>}</tbody></table></Panel></>}
function Metric({label,value,tone=""}){return <article className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong></article>}
function Panel({title,action,children}){return <section className="panel"><div className="panel-title"><h2>{title}</h2>{action}</div>{children}</section>}
function Field({label,wide,children}){return <label className={wide?"wide":""}><span>{label}</span>{children}</label>}
function Select({value,set,items,placeholder}){return <select value={value} onChange={e=>set(e.target.value)} required={!placeholder}><option value="">{placeholder||"Select"}</option>{items.map(x=>{const [v,l]=Array.isArray(x)?x:[x,x];return <option key={v} value={v}>{l}</option>})}</select>}
function LedgerTable({rows,edit,voidEntry}){return <div className="table-wrap"><table><thead><tr><th>Date / ID</th><th>Entry / Account</th><th>Description</th><th>Paid / Received By</th><th>Status</th><th className="right">Amount</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className={r.status==="Void"?"void":""}><td>{r.transaction_date}<small>{r.id}</small></td><td>{r.entry_type||r.kind}<small><code>{r.account_code||"—"}</code> {r.chart_of_accounts?.name||r.category}</small></td><td>{r.description}<small>{r.reference_no}</small></td><td><b>{r.paid_by==="Pradeep"?"Wicky":r.paid_by}</b><small>{r.payment_method}</small></td><td><span className={`pill ${r.status.toLowerCase()}`}>{r.status}</span></td><td className={`right amount ${r.kind.toLowerCase()}`}>{r.kind==="Income"?"+":"−"}{money.format(r.amount)}</td><td><div className="row-actions"><button className="ghost compact" onClick={()=>edit(r)}>Edit</button><button className="danger-link" onClick={()=>voidEntry(r)}>Delete</button></div></td></tr>)}{!rows.length&&<tr><td colSpan="7">No ledger entries found.</td></tr>}</tbody></table></div>}
